# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

before_install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --quiet --name pylandstats python=$TRAVIS_PYTHON_VERSION
  - source activate pylandstats
  - conda install -c conda-forge geopandas descartes fiona=1.8.6 ipykernel nbconvert "python-dateutil<=2.8.0"
  - conda info --all
  - conda list
  - python -m ipykernel install --user --name pylandstats --display-name "Python (pylandstats)"  

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .[geo]
  - pip install -r requirements-dev.txt
  - pip show pylandstats

# command to run tests, e.g. python setup.py test
script:
  - coverage run -p --source pylandstats -m pytest
  - flake8
  - TRANSONIC_NO_REPLACE=1 coverage run -p --source pylandstats -m pytest tests/test_pylandstats.py::TestLandscape::test_transonic
  - git clone https://github.com/martibosch/pylandstats-notebooks
  - cd pylandstats-notebooks
  - make execute_notebooks
  - cd ..  

after_success:
  - coverage combine
  - coverage report -m
  - coveralls

# deploy new versions to PyPI
before_deploy:
  - pip install pythran "transonic>=0.4.0"
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  user: martibosch
  password:
    secure: vID3rBmdfM1X+oSs6gepPq21FZFdAGK0WPa2kZiSU1lNpGD6wvrBU4WGphwhTjZuckwpG0mYFKYrA0M0yw1JgbrLUqSo0JDU64Ev6YQKV/bQDGp7hAoPEx1sHeaB7JKoPvPHDWHvjXP/3qQ8/fZjSmFNx3ZsHH8lQQsb62YUWsSC/+pjE5rfwJjkgHG3i0VVmdRX5zhlu9U0UE0g8nodqDLOOKaaTYwQ8JQyD3hnR9LEN7SRc7Rz/qdvzerDQ+gCgvHrzyGd0KZ4c86Akg9bwkwArZee+YaE7zIbK4bPIgZyLuL3I1pLi5Ybf0UsylAOTU82970CKvoK7VcidgLMdycbjATDyslFWmS/mwyvsfNEF+wQFRXzoBlSZV4AR8CDgulivs72HU3aoFBPjTOIZLVonFU8itkfHNKw2ys0Sj13NV01Z3OIRDmpE738ORsZv4YTp2NaI82B/zhLAKm4MbjTHsNoAyU+fQDiZAiwerLqRO30CzuiRPA9hgLIa9YMbhg+z2kWEnUCLA3173VgHVX0INamvEjZkeHm2/RF0nEm8kOldZEDq5MZ+PkiSDjAlPrsV+4eoP/RYXPh2blC3xzeidd13w/AneDUlwytkKxWOIIWR6UyKyDEplmY+gixydYNXb2b+OEj3MzEKNS45YG9sRtPXmOIuOR8D8HkRQk=
